# compose file for testing the Database sync locally
version: '3.9'

services:
  psql:
    image: postgres:15.1
    container_name: test-db
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=salesforce-test
    networks:
      - backend
  sfdc-backup:
    build:
      context: .
    environment:
      - SQL_DRIVER=postgresql
      - SQL_HOST=test-db
      - SQL_PORT=5432
      - SQL_DB=salesforce-test
      - SQL_USERNAME=postgres
      - SQL_PASSWORD=password
      - sf_username=${sf_username}
      - sf_password=${sf_password}
      - sf_token=${sf_token}
      - OBJECT_LIST=Opportunity
    networks:
      - backend
    links:
      - psql:database
    depends_on:
      - psql

networks:
  backend:
    driver: bridge