version: '3.9'

services:
  psql:
    image: postgres:15.1
    container_name: db
    ports:
    - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=salesforc-test
    networks:
      - backend
  sfdc-backup:
    build:
      context: .
    environment:
      - SQL_DRIVER=postgresql
      - SQL_HOST=db
      - SQL_PORT=5432
      - SQL_DB=salesforce-test
      - SQL_USERNAME=postgres
      - SQL_PASSWORD=password
      - sf_username=${sf_username}
      - sf_passowrd=${sf_password}
      - sf_token=${sf_token}
    networks:
      - backend

networks:
  backend:
    driver: bridge